
# -*- coding: utf-8 -*-
"""Proposal Generator with T5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyYCqmdQd15suuaS0Z_9j9eYfhblhysg

**Few shot text generation with T5 Transformer**

Adopted for risk statement generation from tutorial code originally developed by Ramsri Goutham Golla

Linkedin : https://www.linkedin.com/in/ramsrig/

Twitter: https://twitter.com/ramsri_goutham

## 1. Install libraries
"""



# Check we have a GPU and check the memory size of the GUP
#!nvidia-smi

"""## 2. Prepare Model"""

import random
import pandas as pd
import numpy as np
import os
import torch
from torch.utils.data import Dataset, DataLoader

from transformers import (
    AdamW,
    T5ForConditionalGeneration,
    T5Tokenizer,
    get_linear_schedule_with_warmup
)


#CONSIDER DELETING THIS IMPORT LATER AFTER TESTING ONLINE VERSION
from transformers import AutoTokenizer, AutoModelWithLMHead

def set_seed(seed):
  random.seed(seed)
  np.random.seed(seed)
  torch.manual_seed(seed)

set_seed(42)


#User must save t5 small from hugging face repo into a local folder of the project directory named t5smallCopy
tokenizer = T5Tokenizer.from_pretrained('t5SmallCopy')
t5_model = T5ForConditionalGeneration.from_pretrained('t5SmallCopy')

from transformers import file_utils
print(file_utils.default_cache_path)




# optimizer

no_decay = ["bias", "LayerNorm.weight"]
optimizer_grouped_parameters = [
    {
        "params": [p for n, p in t5_model.named_parameters() if not any(nd in n for nd in no_decay)],
        "weight_decay": 0.0,
    },
    {
        "params": [p for n, p in t5_model.named_parameters() if any(nd in n for nd in no_decay)],
        "weight_decay": 0.0,
    },
]
optimizer = AdamW(optimizer_grouped_parameters, lr=3e-4, eps=1e-8)

# dataset preparation

true_false_adjective_tuples = [
                              	("These process improvements were focused on creating exceptions to the Federal Aviation  Regulations (FAR), and not on creating enduring solutions that might be relevant in the Next  Generation Air Transportation System (NextGen) time frame.","If the process improvements do not help create enduring solutions that might be relevant in the Next Generation Air Transportation System, then Program performance will be negatively impacted."),
("The foundation of what the UAS-NAS Project is planning to deliver  is not expected to change dramatically, but the specifics of the research activity content and final  products may change to better meet these needs.","If the  specifics of research activity content and final products change dramatically, then Program cost and schedule will be negatively impacted."),
("The  UAS-NAS Project will work closely with AOSP to leverage those capabilities that can help enable  UAS access to the NAS.","If the UAS-NAS Project does not work closely with AOSP to leverage those capabilities that can help enable UAS access to the NAS, then Program performance will be negatively impacted."),
("Although some of these characteristics are not unique to UAS, the number of aircraft that possess  them is expected to increase because UAS will be able to fulfill so many new roles.","If the number of aircraft that possess these characteristics increases, then Program cost and schedule could be negatively impacted."),
("In some cases, UAS-NAS Project personnel plan to be the lead for specific sections within the SC-228 Phase 2 MOPS.","If UAS-NAS Project personnel are not the lead for specific sections with the SC-228 Phase 2 MOPS, then Program cost and schedule will be negatively impacted."),
("In some cases, individual  research findings are transferred to several key UAS-NAS Project stakeholders, as  indicated by the label above the milestone.","If individual research findings are not transferred to several key UAS-NAS Project stakeholders, then Program performance will be negatively impacted."),
("The SC-228  Phase 2 MOPS deliverables in turn have the potential to influence the UAS-NAS Project  activities, as shown by the green dashed lines pointing from the upper section of the figure to the lower section of the figure.","If the SC-228  Phase 2 MOPS deliverables do not influence the UAS-NAS Project  activities, then Program cost and schedule will be negatively impacted."),
("For example, ERT  technical decisions and MRB approvals can assist in keeping the technical portfolio relevant to  stakeholder needs, allowing changes to the technical baseline, allowing adjustments to schedule,  and allowing shifts in resources to ensure successful execution.","If ERT technical decisions and MRB approvals don't assist in keeping the technical portfolio relevant to stakeholder needs, then Program cost and schedule will be negatively impacted."),
("The primary aspect of this relationship is to investigate the possibility of sUAS providing  fire detection surveillance of the swamp.","If this relationship fails, then the possibily of sUAS providing fire detection surveillnace of the swamp will be negatively impacted."),
("Subsequently, the C2 Subproject has led multiple studies  to consider spectrum requirements and possible regulatory actions, including allocations, in order  to support safe operation of UAS.","If the C2 Subproject does not continue to lead multiple studies to consider spectrum requirements and possible regulatory actions, including allocations, then Program safety will be negatively impacted."),
("Although  the potential for changes may exist, the Project has taken definitive steps toward mitigating this  potential in Phase 2 through the development of the Phase 1 (FY17 - FY20) Portfolio, which tied  all of the project technical work to the UAS community needs, and by embedding the SPMs within  key groups, such as SC-228, that are shaping the direction of UAS integration into the NAS.",""),
("Existing support service contracts at each of the Aeronautics Centers will likely  represent a considerable percentage of the procurement actions.","If existing support service contracts at each of the Aeronautics Centers don't represent a considerable percentage of the procurement actions, then Program cost and schedule will be negatively impacted."),
("Also, the DAA  subproject plans to establish a cooperative agreement for an alternative surveillance  sensor system.","If the DAA subproject does not establish a cooperative agreement for an alternative surveillance  sensor system, then Program performance will be negatively impacted."),
("Funding of Phase III SBIR may occur if the research is relevant to the UAS-NAS Project  goals.","If the research is not relevant to the UAS-NAS Project  goals, then Program cost and schedule will be negatively impacted."),
("Agreements with standards organizations, industry, and academia may be established.","If agreements with standards organizations, industry, and academia are not established, then the Program performance will be negatively impacted."),
("The project annual review content may be leveraged to support the Program annual  review conducted by the ARMD.","If the project annual review content is not leveraged to support the Program annual  review conducted by the ARMD, then Program performance will be negatively impacted."),
("A look ahead at the next fiscal year that includes key activities and milestones by TC and  potential issues or watch items that may impact project execution in the coming year.","If there isn't a look ahead at the next fiscal year that includes key activities and milestones by TC and  potential issues or watch items that may impact project execution in the coming year, then Program performance will be negatively impacted.")
                                                                                                      

]

"""## 3. Train Loop"""


t5_model.train()

epochs = 10

for epoch in range(epochs):
  print ("epoch ",epoch)
  for input,output in true_false_adjective_tuples:
    input_sent = "falsify: "+input+ " </s>"
    ouput_sent = output+" </s>"

    tokenized_inp = tokenizer.encode_plus(input_sent,  max_length=96, pad_to_max_length=True,return_tensors="pt")
    tokenized_output = tokenizer.encode_plus(ouput_sent, max_length=96, pad_to_max_length=True,return_tensors="pt")


    input_ids  = tokenized_inp["input_ids"]
    attention_mask = tokenized_inp["attention_mask"]

    labels= tokenized_output["input_ids"]
    decoder_attention_mask=  tokenized_output["attention_mask"]


    # the forward function automatically creates the correct decoder_input_ids
    output = t5_model(input_ids=input_ids, labels=labels,decoder_attention_mask=decoder_attention_mask,attention_mask=attention_mask)
    loss = output[0]
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()



"""## 4. Test model"""

test_sent = 'falsify: The contractor shall assist ACAT I programs in the development of Selected Acquisition Reports (SARs) at Milestone B, and annually thereafter, or at the end of the quarter following an APB breach. </s>'
test_tokenized = tokenizer.encode_plus(test_sent, return_tensors="pt")

test_input_ids  = test_tokenized["input_ids"]
test_attention_mask = test_tokenized["attention_mask"]

t5_model.eval()
beam_outputs = t5_model.generate(
    input_ids=test_input_ids,attention_mask=test_attention_mask,
    max_length=64,
    early_stopping=True,
    num_beams=10,
    num_return_sequences=3,
    no_repeat_ngram_size=2
)

for beam_output in beam_outputs:
    sent = tokenizer.decode(beam_output, skip_special_tokens=True,clean_up_tokenization_spaces=True)
    print (sent)

test_sent = 'falsify: They shall provide a complete list of all accomplishments from the month prior in the form of a status report and reccomend ideal maintenance strategies. </s>'
test_tokenized = tokenizer.encode_plus(test_sent, return_tensors="pt")

test_input_ids  = test_tokenized["input_ids"]
test_attention_mask = test_tokenized["attention_mask"]

t5_model.eval()
beam_outputs = t5_model.generate(
    input_ids=test_input_ids,attention_mask=test_attention_mask,
    max_length=64,
    early_stopping=True,
    num_beams=10,
    num_return_sequences=3,
    no_repeat_ngram_size=2
)

for beam_output in beam_outputs:
    sent = tokenizer.decode(beam_output, skip_special_tokens=True,clean_up_tokenization_spaces=True)
    print (sent)

test_sent = 'falsify: The contractor shall ensure that all databases that use database management systems (DBMS) designed, implemented, and/or hosted on servers and/or mainframes supporting Navy applications and systems be registered in DADMS and are FAM approved </s>'
test_tokenized = tokenizer.encode_plus(test_sent, return_tensors="pt")

test_input_ids  = test_tokenized["input_ids"]
test_attention_mask = test_tokenized["attention_mask"]

t5_model.eval()
beam_outputs = t5_model.generate(
    input_ids=test_input_ids,attention_mask=test_attention_mask,
    max_length=64,
    early_stopping=True,
    num_beams=10,
    num_return_sequences=3,
    no_repeat_ngram_size=2
)

for beam_output in beam_outputs:
    sent = tokenizer.decode(beam_output, skip_special_tokens=True,clean_up_tokenization_spaces=True)
    print (sent)

test_sent = 'falsify: The contractor team must have personnel with experience using various databases. </s>'
test_tokenized = tokenizer.encode_plus(test_sent, return_tensors="pt")

test_input_ids  = test_tokenized["input_ids"]
test_attention_mask = test_tokenized["attention_mask"]

t5_model.eval()
beam_outputs = t5_model.generate(
    input_ids=test_input_ids,attention_mask=test_attention_mask,
    max_length=64,
    early_stopping=True,
    num_beams=10,
    num_return_sequences=3,
    no_repeat_ngram_size=2
)

for beam_output in beam_outputs:
    sent = tokenizer.decode(beam_output, skip_special_tokens=True,clean_up_tokenization_spaces=True)
    print (sent)



#Change path below to your desired local output folder
savepath = r'D:\FlaskVisualStudioTest\FlaskWebProject1\FlaskWebProject1\FlaskWebProject1\t5SmallCopyNASARisk2'
t5_model.save_pretrained(savepath)



